version: "3.1"

services:
  adminer:
    image: adminer
    restart: always
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.danlab.ru`)

networks:
  web:
    external: true
